apiVersion: apps/v1
kind: Deployment
metadata:
  name: totem
spec:
  replicas: 1
  selector:
    matchLabels:
      app: totem
  template:
    metadata:
      labels:
        app: totem
    spec:
      containers:
      - name: totem
        image: mofeimw/totem:latest
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 512Mi
